### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by terremoth** [smjburton/v_JSON#1]
Hello! I would like to know more how your json parser works!
I am interested.
Do you have plans to make a documentation for it?

Regards,
Lucas.

**Comment by Greg-Hamel** [comment]
I am quite interested as well, would love to hear more from @smjburton

**Comment by smjburton** [comment]
Hello, I will try to add documentation in the coming months. In the meantime, I've included a basic implementation in the README for the project. Let me know if there's anything specific I can help you out with.

Thanks,
Scott

**Comment by terremoth** [comment]
Nice!
